### ISSUE TITLE
Faster search box transition

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/property2#23]
From @atogle, who likes things zippy:

``` css
.smooth {
  transition: width 0.3s;
  white-space: nowrap;
}
```
